/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-02-23 05:52:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.js;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ajax_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>ajax</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>Ajax개요</h1>\r\n");
      out.write("	<!-- \r\n");
      out.write("		Asynchgronous JavaScript And XML\r\n");
      out.write("		 - 서버로부터 데이터를 가져와 전체 페이지를 새로 고치지 않고\r\n");
      out.write("		   일부분만 로드할 수 있게 하는 기법.\r\n");
      out.write("		 - A태그나 Form태그를 통한 요청은 동기식 요청방식이라고 부른다.\r\n");
      out.write("		   (응답결과가 돌아와야 볼 수 있다.)\r\n");
      out.write("		   \r\n");
      out.write("		* 동기식 / 비동기식\r\n");
      out.write("		 - 동기식 : 요청 처리 후 그에 해당하는 응답 페이지가 돌아와야만 그 다음 작업이 가능\r\n");
      out.write("		 만약 서버에서 호출된 결과까지의 시간이 지연되면 그 시간동안 대기해야 한다.\r\n");
      out.write("		 항상 전체 페이지가 리로드 된다.\r\n");
      out.write("		  \r\n");
      out.write("		 - 비동기식\r\n");
      out.write("		  - 현재 페이지를 그대로 유지하면서 중간중간마다 추가적인 요청을 보내줄 수 있다.\r\n");
      out.write("		  - 검색어 자동완성기능, 아이디중복체크기능, 실시간 검색 기능\r\n");
      out.write("		  - 서버에서 결과를 반환해주기까지 오랜시간이 걸리더라도 현재 페이지를 이용하는데\r\n");
      out.write("		  문제가 없다.\r\n");
      out.write("		 \r\n");
      out.write("		 \r\n");
      out.write("	 -->\r\n");
      out.write("	<h1>XMLHttpRequest 객체를 이용한 ajax</h1>\r\n");
      out.write("	<button onclick=\"ajaxTest1()\">ajax get</button>\r\n");
      out.write("	<button onclick=\"ajaxTest2()\">ajax post</button>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"target\"></div>\r\n");
      out.write("	<script>\r\n");
      out.write("		// XmlHttpRequest를 이용한 비동기 통신\r\n");
      out.write("		function ajaxTest1() {\r\n");
      out.write("			//1. XmlHttpRequest객체 생성\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("\r\n");
      out.write("			//2. xhr객체 설정\r\n");
      out.write("			// open(\"전송방식\",\"주소\",[동기/비동기])\r\n");
      out.write("			xhr.open(\"get\", \"/ajax/ajaxTest.do?id=admin\");\r\n");
      out.write("\r\n");
      out.write("			//3. 요청에 대한 응답결과를 처리할 이벤트 리스너 기술\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				// readystate : 전송상태를 관리하는 속성\r\n");
      out.write("				if (xhr.readyState == 4) { // 요청성공\r\n");
      out.write("					// xhr.status 응답결과를 관리하는 속성\r\n");
      out.write("					// 응답성공시(200)\r\n");
      out.write("					// status응답 상태값\r\n");
      out.write("					if (xhr.status == 200) {\r\n");
      out.write("						// 정상수신시 응답데이터가 담기는 영역\r\n");
      out.write("						console.log(xhr.responseText);\r\n");
      out.write("						target.innerHTML = \"<h3>\" + xhr.responseText + \"</h3>\"\r\n");
      out.write("						// 응답실패시(404)\r\n");
      out.write("					} else if (xhr.status == 404) {\r\n");
      out.write("						alert(\"찾는 페이지가 존재하지 않습니다.\");\r\n");
      out.write("					} else {\r\n");
      out.write("						alert(\"에러 발생\");\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("\r\n");
      out.write("			//4. 객체를 활용하여 요청보내기\r\n");
      out.write("			xhr.send();\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function ajaxTest2() {\r\n");
      out.write("			const xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"post\", \"/ajax/ajaxTest.do\");\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState == 4) {\r\n");
      out.write("					if (xhr.status == 200) {\r\n");
      out.write("						target.innerHTML = `<h3>POST : ${xhr.responseText}</h3>`;\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			// body영역에 담긴 데이터의 형식을 기술\r\n");
      out.write("			xhr.setRequestHeader(\"Content-Type\",\r\n");
      out.write("					\"application/x-www-form-urlencoded\");\r\n");
      out.write("			xhr.send(\"id=user01\"); // send의 매개변수가 body영역\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<h1>fetch함수를 이용한 AJAX</h1>\r\n");
      out.write("	<button onclick=\"fetch1()\">Fetch Get테스트</button>\r\n");
      out.write("	<button onclick=\"fetch2()\">Fetch Post테스트</button>\r\n");
      out.write("	<div id=\"target2\"></div>\r\n");
      out.write("	<script>\r\n");
      out.write("			function fetch1(){\r\n");
      out.write("				/*\r\n");
      out.write("					fetch함수\r\n");
      out.write("					 - es6에서 추가된 비동기 함수로, 간결한 문법으로 서버와 통신\r\n");
      out.write("					 할 수 있다.\r\n");
      out.write("					 - Promise기반으로 설계되어 있으며 비동기 요청 성공시, 실패시 처리를\r\n");
      out.write("					 위한 메서드를 제공한다.\r\n");
      out.write("					 - fetch함수는 비동기 요청을 보내면 Promise객체를 반환하고, 서버로\r\n");
      out.write("					 부터 데이터를 응답받기 전까지 다른작업을 수행할 수 있다.\r\n");
      out.write("					 \r\n");
      out.write("					 Promise\r\n");
      out.write("					  - 비동기 작업의 처리결과를 나타내는 객체로 3가지 상태값을 가진다.\r\n");
      out.write("					  1) pending : 비동기 작업을 처리중인 상태(초기값)\r\n");
      out.write("					  2) resolved : 비동기 작업 처리 완료 상태(응답받은상태)\r\n");
      out.write("					  3) rejected : 비동기 작업 처리 실패 상태(응답x)\r\n");
      out.write("				*/\r\n");
      out.write("				// fetch(url,[options])\r\n");
      out.write("				// - options: 요청에 대한 옵션(method, headers, body...)\r\n");
      out.write("				fetch(\"/ajax/ajaxTest.do?id=admin\")\r\n");
      out.write("					.then(function(response){ // 요청 성공시 실행할 함수\r\n");
      out.write("						console.log(response);\r\n");
      out.write("						if(!(response.ok && response.status === 200)){\r\n");
      out.write("							throw new Error('에러발생');\r\n");
      out.write("						}\r\n");
      out.write("						return response.text(); // text()함수는 Promise를 반환\r\n");
      out.write("					})\r\n");
      out.write("					.then(function(text){\r\n");
      out.write("						target2.innerHTML = text;\r\n");
      out.write("					})\r\n");
      out.write("					.catch(function(error){ // Promise객체의 결과가 reject되는경우 실행\r\n");
      out.write("						console.log(error);\r\n");
      out.write("					})\r\n");
      out.write("					.finally(function(){// 비동기 작업이 처리 완료되는 경우 항상 실행하는 함수\r\n");
      out.write("						console.log('작업 완료');\r\n");
      out.write("					});\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			function fetch2(){\r\n");
      out.write("				fetch('/ajax/ajaxTest.do', {\r\n");
      out.write("					method:'post',\r\n");
      out.write("					body : \"id=user01&name=mkm\",\r\n");
      out.write("					headers : {\r\n");
      out.write("						\"Content-type\" : \"application/x-www-form-urlencoded\"\r\n");
      out.write("					}\r\n");
      out.write("				})\r\n");
      out.write("				.then( function(response){\r\n");
      out.write("					return response.text();\r\n");
      out.write("				})\r\n");
      out.write("				.then( function(text) {\r\n");
      out.write("					target2.innerHTML = `<h4>Fetch Post : ${text}</h4>`;\r\n");
      out.write("				})\r\n");
      out.write("			}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
